### ISSUE TITLE
ERROR: wlan1mon card could not be started! 

### ISSUE THREAD

**Issue by krll-k** [d4rkcat/HandShaker#6]
[*] Started wlan1mon monitor on enable

 [*] ERROR: wlan1mon card could not be started! 

 [*] Monitor wlan1mon: removed. 

[ ok ] Starting networking (via systemctl): networking.service.
 [*] All monitor devices have been shut down, Goodbye...

**Comment by schmorrison** [comment]
I believe I am facing the same issue. Beyond that error, its hard to say whether it comes from the exact same genesis.
I had believed I tracked it down to the new udev rules for naming network interfaces, eg. "wlan0" is now "wlx{MAC_ADDRESS}", however HandShaker greps for wlan in a number of places, when changing TX power for example. I found an article describing how to reinstate the old naming policy. You can follow it here: https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/ Since the old behavior, eg. "wlan0", is not preferred, it probably would be best to change the script to grep for wlx{MAC_ADDRESS} interface names. This fix, while easier to actually manage my interfaces mentally, did not result in HandShaker starting wlan1mon correctly, though it maybe saved me down the line with the wlan grepping problem mentioned above.

This line, 
`echo $GRN;MON1=$(airmon-ng start $NIC | grep monitor | cut -d ' ' -f 5 | head -c -2);echo " [*] Started $NIC monitor on $MON1"`
 was the problem it seems. `| cut -d ' ' -f 5 |`  pulls "enable" instead of the interface name. By changing all 3 occurrences of the line above(251, 253, 264) to 
`echo $GRN;MON1=$(airmon-ng start $NIC | grep monitor | cut -d ' ' -f 9 | head -c -2 | cut -d ']' -f 2);echo " [*] Started $NIC monitor on $MON1`
HandShaker correctly greps the monitor interface names from airmon-ng and begins sniping.

This is likely due to a more verbose output from airmon-ng when starting the interface than HandShaker is used to.

**Comment by d4rkcat** [comment]
https://github.com/d4rkcat/HandShaker/issues/5

This is the same problem
